# Generated by Django 4.1.13 on 2024-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_tax_tax_percentage_checkbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
