# Generated by Django 4.1.13 on 2024-04-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tax_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='picture',
            new_name='image',
        ),
    ]
