# Generated by Django 4.1.13 on 2024-04-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_picture_mall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='company_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.companygroup'),
            preserve_default=False,
        ),
    ]
