# Generated by Django 4.1.13 on 2024-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_businessprofile_company_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
