# Generated by Django 4.1.13 on 2024-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_module_name_alter_module_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondate',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessiondate',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessiondate',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessiondate',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
