# Generated by Django 4.1.13 on 2024-04-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_employee_basic_pay_alter_employee_emirates_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnerRepeater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inner_text_input", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OuterRepeater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_input", models.CharField(max_length=100)),
                (
                    "inner_repeater",
                    models.ManyToManyField(
                        related_name="outer_repeaters", to="account.innerrepeater"
                    ),
                ),
            ],
        ),
    ]
