# Generated by Django 4.1.13 on 2024-05-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_bird'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bird',
        ),
    ]
