# Generated by Django 4.1.13 on 2024-05-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_delete_bird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondate',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.session'),
        ),
    ]
