# Generated by Django 4.1.13 on 2024-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_sessiondate_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionschedule",
            name="current_date",
            field=models.DateField(null=True),
        ),
    ]
